sudo: false

# Enable c++ support
language: cpp

# Cache
cache:
  directories:
    - $HOME/Library/Caches/Homebrew


# Compiler selection
matrix:
  include:
    - os: osx
      env:
        - CXX_COMPILER=clang++
        - C_COMPILER=clang
        - HOMEBREW_CC=clang
        - HOMEBREW_CXX=clang++
    - os: osx
      env:
        - CXX_COMPILER=g++-7
        - C_COMPILER=gcc-7
        - HOMEBREW_CC=gcc-7
        - HOMEBREW_CXX=g++-7
    # - os: linux
    #   dist: trusty




# Git options
git:
  submodules: false

branches:
  only:
  - develop


# Updates
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install gcc; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install mpich; fi
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX
  - which $CXX_COMPILER


before_script:
  - mkdir build
  - cd build

# Build steps
script:
  - cmake ../ -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER
  - make -j build-tests
  - make test
