sudo: false

# Git options
git:
  submodules: false

# Enable c++ support
language: cpp

# # Cache
# cache:
#   directories:
#     - $HOME/Library/Caches/Homebrew


# Compiler selection
matrix:
  include:
    # Tests on osx
    - os: osx
      env:
        - CXX_COMPILER=clang++
        - C_COMPILER=clang
      install:
        - brew install mpich
    - os: osx
      env:
        - CXX_COMPILER=g++-7
        - C_COMPILER=gcc-7
      install:
        - brew install gcc
        - brew install mpich
    - os: osx
      env:
        - CXX_COMPILER=clang++
        - C_COMPILER=clang
      install:
    - os: osx
      env:
        - CXX_COMPILER=g++-7
        - C_COMPILER=gcc-7
      install:
        - brew install gcc

    # Tests on linux
    - os: linux
      dist: trusty
      env:
        - CXX_COMPILER=g++-4.9
        - C_COMPILER=gcc-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - cmake
            - openmpi-bin
            - openmpi-dev
            - libblas-dev
            - liblapack-dev
            # - libmumps-dev
            - libsuitesparse-dev

    - os: linux
      dist: trusty
      env:
        - CXX_COMPILER=clang++-3.6
        - C_COMPILER=clang-3.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - cmake
            - openmpi-bin
            - openmpi-dev
            - libblas-dev
            - liblapack-dev
            # - libmumps-dev
            - libsuitesparse-dev

    - os: linux
      dist: trusty
      env:
        - CXX_COMPILER=g++-4.9
        - C_COMPILER=gcc-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - cmake
            - mpich
            - libmpich-dev
            - libblas-dev
            - liblapack-dev
            # - libmumps-dev
            - libsuitesparse-dev

    - os: linux
      dist: trusty
      env:
        - CXX_COMPILER=clang++-3.6
        - C_COMPILER=clang-3.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - cmake
            - mpich
            - libmpich-dev
            - libblas-dev
            - liblapack-dev
            # - libmumps-dev
            - libsuitesparse-dev





# Updates
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew cask uninstall oclint; fi # incompatibility with a previously installed oclint and gcc
  # - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install gcc; fi
  # - if [ "$TRAVIS_OS_NAME" == "osx" ]; then HOMEBREW_BUILD_FROM_SOURCE=1 brew install homebrew/science/mumps; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install suite-sparse; fi
  - cd .. && git clone https://github.com/hpddm/hpddm.git && cd htool



before_script:
  - which $CXX_COMPILER
  - mkdir build
  - cd build

# Build steps
script:
  - CC=$C_COMPILER CXX=$CXX_COMPILER cmake ../
  - make -j build-tests
  - ctest --output-on-failure
