sudo: false

# Enable c++ support
language: cpp


# Compiler selection
matrix:
  include:
    - os: osx
      env:
        - MATRIX_EVAL="brew install mpich && CC=clang && CXX=clang++"
    - os: osx
      env:
        - MATRIX_EVAL="brew install mpich && CC=gcc-7 && CXX=g++-7"
    # - os: linux
    #   compiler: clang



# Git options
git:
  submodules: false

branches:
  only:
  - develop


# Updates
before_install:
  - eval "${MATRIX_EVAL}"

# Build steps
script:
  - mkdir build && cd build
  - cmake ../
  - make -j build-tests
  - make test
