sudo: false

# Enable c++ support
language: cpp

# OS
os:
  - linux
  - osx

dist: trusty

# Compiler selection
compiler:
  - clang


matrix:
  include:
    - os: osx
      compiler: gcc-7
    - os: linux
      compiler: gcc



# Git options
git:
  submodules: false

branches:
  only:
  - develop


# Updates
before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install mpich; fi

# Build steps
script:
  - mkdir build && cd build
  - cmake ../
  - make -j build-tests
  - make test
