sudo: false

# Enable c++ support
language: cpp

# # Cache
# cache:
#   directories:
#     - $HOME/Library/Caches/Homebrew


# Compiler selection
matrix:
  include:
    # - os: osx
    #   env:
    #     - CXX_COMPILER=clang++
    #     - C_COMPILER=clang
    # - os: osx
    #   env:
    #     - CXX_COMPILER=g++-7
    #     - C_COMPILER=gcc-7
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          packages:
            - libmpich-dev




# Git options
git:
  submodules: false

branches:
  only:
  - develop


# Updates
install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install gcc; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install mpich; fi



before_script:
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX
  - which $CXX_COMPILER
  - mkdir build
  - cd build

# Build steps
script:
  - cmake ../ -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER
  - make -j build-tests
  - make test
