sudo: false

# Git options
git:
  submodules: false

# Enable c++ support
language: cpp

# # Cache
# cache:
#   directories:
#     - $HOME/Library/Caches/Homebrew


# Compiler selection
matrix:
  include:
    # Tests on osx
    - os: osx
      env:
        - CXX=clang++
        - CC=clang
      install:
        - brew install mpich
        - brew install suite-sparse
        # - brew reinstall python
        - pip3 install pytest

    ## mpich does not work anymore with gcc
    ## it would need to be compiled with gcc...
    # - os: osx
    #   env:
    #     - CXX_COMPILER=g++-7
    #     - C_COMPILER=gcc-7
    #   install:
    #     - brew install gcc
    #     - brew install mpich
    - os: osx
      env:
        - CXX=clang++
        - CC=clang
        - MPIEXEC_PREFLAGS=-oversubscribe
      install:
        - brew install openmpi
        - brew install suite-sparse
        # - brew reinstall python
        - pip3 install pytest

    - os: osx
      env:
        - CXX_COMPILER=g++-9
        - C_COMPILER=gcc-9
        - MPIEXEC_PREFLAGS=-oversubscribe
      install:
        # - brew install gcc
        - brew install openmpi
        - brew install suite-sparse
        # - brew reinstall python
        - pip3 install pytest

    - os: linux
      env: PYTHON=3.8
      dist: xenial
      group: travis_latest
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - mpich
            - libmpich-dev
            - libblas-dev
            - liblapack-dev
            - libsuitesparse-dev
      install:
        - pip3 install pytest

    - os: linux
      env: PYTHON=3.8
      dist: xenial
      group: travis_latest
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - mpich
            - libmpich-dev
            - libblas-dev
            - liblapack-dev
            - libsuitesparse-dev
      install:
        - pip3 install pytest


    - os: linux
      env: PYTHON=3.8
      dist: xenial
      group: travis_latest
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - openmpi-bin
            - libopenmpi-dev
            - libblas-dev
            - liblapack-dev
            - libsuitesparse-dev
      install:
        - pip3 install pytest


    - os: linux
      env: PYTHON=3.8
      dist: xenial
      group: travis_latest
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - openmpi-bin
            - libopenmpi-dev
            - libblas-dev
            - liblapack-dev
            - libsuitesparse-dev
      install:
        - pip3 install pytest




# Updates
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew upgrade cmake; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export LD_LIBRARY_PATH=$(if [[ $CC == "clang" ]]; then echo -n '/usr/local/clang/lib'; fi); fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then pyenv versions; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then pyenv shell  ${PYTHON}; fi
  - cd .. && git clone https://github.com/hpddm/hpddm.git && cd htool



before_script:
  - which $CXX
  - mkdir build
  - cd build

# Build steps
script:
  - cmake ../ -DMPIEXEC_PREFLAGS=${MPIEXEC_PREFLAGS}
  - make -j build-tests
  - export OMP_NUM_THREADS=2
  - ctest --output-on-failure
  - cd ..
  - pip3 install . --user
  - pytest python_tests
  - mpirun -np 2 ${MPIEXEC_PREFLAGS} pytest python_tests
  - mpirun -np 4 ${MPIEXEC_PREFLAGS} pytest python_tests

