sudo: false

# Enable c++ support
language: cpp


# Compiler selection
matrix:
  include:
    - os: osx
      compiler: clang
    - os: osx
      compiler: gcc
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"
    # - os: linux
    #   compiler: clang



# Git options
git:
  submodules: false

branches:
  only:
  - develop


# Updates
before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install mpich; fi

# Build steps
script:
  - mkdir build && cd build
  - cmake ../
  - make -j build-tests
  - make test
